/**
 * YonderClaw Auto-Start — named sessions that survive reboots
 *
 * Creates:
 * 1. A named Claude Code session for the agent
 * 2. A startup script that auto-launches and resumes that session
 * 3. Task Scheduler entries for background jobs (inbox, follow-ups)
 *
 * The user never has to manually open Claude or remember session IDs.
 */

import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import os from "os";
import * as clack from "@clack/prompts";
import { brand, muted, success, status } from "./brand.js";
import type { SystemInfo } from "./detect.js";

export type AutoStartConfig = {
  clawName: string;       // User-chosen name, e.g. "SalesBot", "ResearchAgent"
  sessionName: string;    // Sanitized for file paths
  projectDir: string;
  claudePath: string;     // Full path to claude.exe
  startOnBoot: boolean;
  backgroundTasks: Array<{
    name: string;
    script: string;
    intervalMinutes: number;
    businessHoursOnly: boolean;
  }>;
};

/**
 * Ask the user to name their agent and configure auto-start.
 */
export async function configureAutoStart(
  projectDir: string,
  systemInfo: SystemInfo
): Promise<AutoStartConfig | null> {
  const clawName = await clack.text({
    message: "Name your agent (this is what it calls itself)",
    placeholder: "Atlas",
    defaultValue: "Atlas",
  });
  if (clack.isCancel(clawName)) return null;

  const startOnBoot = await clack.confirm({
    message: "Start this agent automatically when your PC boots?",
    initialValue: true,
  });
  if (clack.isCancel(startOnBoot)) return null;

  // Find Claude executable
  const claudePath = findClaudePath(systemInfo);

  const sessionName = (clawName as string).toLowerCase().replace(/[^a-z0-9]/g, "-");

  return {
    clawName: clawName as string,
    sessionName,
    projectDir,
    claudePath,
    startOnBoot: startOnBoot as boolean,
    backgroundTasks: [
      { name: "InboxCheck", script: "src/inbox.ts", intervalMinutes: 30, businessHoursOnly: false },
      { name: "FollowUps", script: "src/run-followups.ts", intervalMinutes: 120, businessHoursOnly: true },
    ],
  };
}

/**
 * Find the Claude Code executable path.
 */
function findClaudePath(systemInfo: SystemInfo): string {
  const candidates = [
    path.join(systemInfo.user.homedir, ".local", "bin", "claude.exe"),
    path.join(systemInfo.user.homedir, ".local", "bin", "claude"),
    "claude",
  ];

  for (const p of candidates) {
    try {
      const resolved = execSync(`where "${p}" 2>nul || which "${p}" 2>/dev/null`, {
        encoding: "utf-8",
        timeout: 3000,
      }).trim().split("\n")[0];
      if (resolved) return resolved;
    } catch {}
  }

  // Check if the local path exists directly
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }

  return candidates[0]; // Best guess
}

/**
 * Create all auto-start scripts and register them.
 */
export function setupAutoStart(config: AutoStartConfig, systemInfo: SystemInfo): void {
  const platform = systemInfo.os.platform;

  if (platform === "Windows") {
    setupWindowsAutoStart(config);
  } else if (platform === "Linux") {
    setupLinuxAutoStart(config);
  } else if (platform === "macOS") {
    setupMacAutoStart(config);
  }
}

// ═══════════════════════════════════════
//  WINDOWS
// ═══════════════════════════════════════

function setupWindowsAutoStart(config: AutoStartConfig) {
  const scriptsDir = path.join(config.projectDir, "scripts");
  fs.mkdirSync(scriptsDir, { recursive: true });

  // 1. Create the agent launcher script
  const launcherPath = path.join(scriptsDir, `launch-${config.sessionName}.bat`);
  fs.writeFileSync(launcherPath, `@echo off
REM === YonderClaw Agent Launcher: ${config.clawName} ===
REM Auto-launches Claude Code and resumes the agent session.
REM Generated by YonderClaw Installer v1.0.0

title YonderClaw: ${config.clawName}
cd /d "${config.projectDir}"

echo.
echo   Starting ${config.clawName}...
echo   Session: ${config.sessionName}
echo.

REM Try to continue the last session, or start a new one
"${config.claudePath}" --continue --yes -p "You are ${config.clawName}, a YonderClaw autonomous agent. Read CLAUDE.md for your full configuration. Resume your tasks. Check HEARTBEAT.md for your scheduled checklist. Run any pending tasks."

REM If --continue fails (no prior session), start fresh
if %ERRORLEVEL% neq 0 (
  "${config.claudePath}" --yes -p "You are ${config.clawName}, a YonderClaw autonomous agent. Read CLAUDE.md for your full configuration and begin your work. Check HEARTBEAT.md for your scheduled checklist."
)

REM Restart on exit (keeps the agent alive)
echo.
echo   ${config.clawName} exited. Restarting in 10 seconds...
timeout /t 10 /nobreak >nul
goto :start

:start
"${config.claudePath}" --continue --yes -p "You are ${config.clawName}. Resume your tasks. Check HEARTBEAT.md."
goto :start
`);

  // 2. Create a VBS wrapper to launch hidden (no visible window)
  const vbsPath = path.join(scriptsDir, `launch-${config.sessionName}.vbs`);
  fs.writeFileSync(vbsPath, `' YonderClaw Silent Launcher: ${config.clawName}
' Starts the agent in a minimized window
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "${launcherPath.replace(/\\/g, "\\\\")}" & chr(34), 7, False
`);

  // 3. Background task scripts
  for (const task of config.backgroundTasks) {
    const taskBat = path.join(scriptsDir, `${task.name.toLowerCase()}.bat`);
    fs.writeFileSync(taskBat, `@echo off
cd /d "${config.projectDir}"
npx tsx ${task.script} >> "data\\logs\\${task.name.toLowerCase()}.log" 2>&1
`);
  }

  // 4. Register with Task Scheduler
  if (config.startOnBoot) {
    try {
      // Agent launcher — runs on logon
      execSync(
        `schtasks /create /tn "YonderClaw-${config.sessionName}" /tr "\\"${vbsPath}\\"" /sc ONLOGON /ru "%USERNAME%" /f`,
        { stdio: "pipe" }
      );
      console.log(status.ok(`Auto-start on login: YonderClaw-${config.sessionName}`));
    } catch {
      console.log(status.warn("Could not create logon task (run as Administrator)"));

      // Fallback: add to Startup folder
      const startupDir = path.join(os.homedir(), "AppData", "Roaming", "Microsoft", "Windows", "Start Menu", "Programs", "Startup");
      try {
        const shortcutPath = path.join(startupDir, `YonderClaw-${config.sessionName}.vbs`);
        fs.copyFileSync(vbsPath, shortcutPath);
        console.log(status.ok(`Added to Startup folder: ${shortcutPath}`));
      } catch {
        console.log(status.warn("Could not add to Startup folder either"));
      }
    }

    // Background tasks
    for (const task of config.backgroundTasks) {
      try {
        const taskBat = path.join(scriptsDir, `${task.name.toLowerCase()}.bat`);
        const schedArgs = task.businessHoursOnly
          ? `/sc MINUTE /mo ${task.intervalMinutes} /st 08:00 /et 18:00`
          : `/sc MINUTE /mo ${task.intervalMinutes}`;

        execSync(
          `schtasks /create /tn "YonderClaw-${config.sessionName}-${task.name}" /tr "\\"${taskBat}\\"" ${schedArgs} /ru "%USERNAME%" /f`,
          { stdio: "pipe" }
        );
        console.log(status.ok(`Scheduled: ${task.name} every ${task.intervalMinutes}m${task.businessHoursOnly ? " (business hours)" : ""}`));
      } catch {
        console.log(status.warn(`Could not schedule ${task.name} (run as Administrator)`));
      }
    }
  }

  // 5. Create a stop script
  const stopPath = path.join(scriptsDir, `stop-${config.sessionName}.bat`);
  fs.writeFileSync(stopPath, `@echo off
echo Stopping ${config.clawName}...
schtasks /end /tn "YonderClaw-${config.sessionName}" 2>nul
schtasks /end /tn "YonderClaw-${config.sessionName}-InboxCheck" 2>nul
schtasks /end /tn "YonderClaw-${config.sessionName}-FollowUps" 2>nul
taskkill /f /fi "WINDOWTITLE eq YonderClaw: ${config.clawName}" 2>nul
echo ${config.clawName} stopped.
pause
`);

  // 6. Create a status script
  const statusPath = path.join(scriptsDir, `status-${config.sessionName}.bat`);
  fs.writeFileSync(statusPath, `@echo off
echo === ${config.clawName} Status ===
echo.
schtasks /query /tn "YonderClaw-${config.sessionName}" /fo LIST 2>nul || echo Agent launcher: Not scheduled
echo.
schtasks /query /tn "YonderClaw-${config.sessionName}-InboxCheck" /fo LIST 2>nul || echo Inbox check: Not scheduled
echo.
cd /d "${config.projectDir}"
npx tsx src/agent.ts --status
pause
`);

  console.log("");
  console.log(status.info(`Launcher: scripts/launch-${config.sessionName}.bat`));
  console.log(status.info(`Stop: scripts/stop-${config.sessionName}.bat`));
  console.log(status.info(`Status: scripts/status-${config.sessionName}.bat`));
}

// ═══════════════════════════════════════
//  LINUX (systemd)
// ═══════════════════════════════════════

function setupLinuxAutoStart(config: AutoStartConfig) {
  const serviceFile = `[Unit]
Description=YonderClaw Agent: ${config.clawName}
After=network.target

[Service]
Type=simple
WorkingDirectory=${config.projectDir}
ExecStart=${config.claudePath} --continue --yes -p "You are ${config.clawName}. Resume tasks. Check HEARTBEAT.md."
Restart=always
RestartSec=10
Environment=HOME=${os.homedir()}

[Install]
WantedBy=default.target
`;

  const servicePath = path.join(config.projectDir, "scripts", `yonderclaw-${config.sessionName}.service`);
  fs.writeFileSync(servicePath, serviceFile);

  console.log(status.info("Systemd service file created."));
  console.log(status.info("To enable:"));
  console.log(muted(`  cp ${servicePath} ~/.config/systemd/user/`));
  console.log(muted(`  systemctl --user enable yonderclaw-${config.sessionName}`));
  console.log(muted(`  systemctl --user start yonderclaw-${config.sessionName}`));

  // Cron for background tasks
  const cronLines = config.backgroundTasks.map((t) => {
    const cron = t.businessHoursOnly
      ? `*/${t.intervalMinutes} 8-18 * * *`
      : `*/${t.intervalMinutes} * * * *`;
    return `${cron} cd ${config.projectDir} && npx tsx ${t.script} >> data/logs/${t.name.toLowerCase()}.log 2>&1`;
  });

  const cronPath = path.join(config.projectDir, "scripts", "crontab.txt");
  fs.writeFileSync(cronPath, cronLines.join("\n") + "\n");
  console.log(status.info(`Crontab: crontab ${cronPath}`));
}

// ═══════════════════════════════════════
//  macOS (launchd)
// ═══════════════════════════════════════

function setupMacAutoStart(config: AutoStartConfig) {
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.yonderclaw.${config.sessionName}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${config.claudePath}</string>
    <string>--continue</string>
    <string>--yes</string>
    <string>-p</string>
    <string>You are ${config.clawName}. Resume tasks. Check HEARTBEAT.md.</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${config.projectDir}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${config.projectDir}/data/logs/agent.log</string>
  <key>StandardErrorPath</key>
  <string>${config.projectDir}/data/logs/agent-error.log</string>
</dict>
</plist>`;

  const plistPath = path.join(config.projectDir, "scripts", `com.yonderclaw.${config.sessionName}.plist`);
  fs.writeFileSync(plistPath, plist);

  console.log(status.info("LaunchAgent plist created."));
  console.log(status.info("To enable:"));
  console.log(muted(`  cp ${plistPath} ~/Library/LaunchAgents/`));
  console.log(muted(`  launchctl load ~/Library/LaunchAgents/com.yonderclaw.${config.sessionName}.plist`));
}
